:icons: font
:allow-uri-read:
//caminho padrão para imagens
:imagesdir: images
:numbered:
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


link:https://fagno.github.io/poo-java/[HOME]

= Programação Orientada a Objetos

Fagno Alves Fonseca <fagno.fonseca@ifto.edu.br>
Mestre em Modelagem Computacional de Sistemas – UFT.

== Técnicas de programação tradicionais

As técnicas de programação tradicionais, leva o desenvolvedor a decompor o sistema em partes menores (funções), criando um emaranhado de inúmeras funções que chamam umas às outras.

Geralmente não há separação de conceitos e responsabilidades, causando dependências enormes no sistema, dificultando futuras manutenções no código do programa.

Não existe muito reaproveitamento de código, ao contrário, muitas vezes se tem muito código duplicado. 

Porém, a analise e projeto estruturados, quando corretamente usados, melhoram muito a qualidade final dos softwares.

== O que é POO?

Programação Orientada a Objetos (POO), eleva a programação e o desenvolvimento de sistemas para um novo patamar.

A OO é um mecanismo moderno que ajuda a definir a estrutura de programas baseada nos conceitos do mundo real, sejam eles reais ou abstratos.

Orientação a objetos pode ser resumida como um estilo de desenvolvimento baseado no conceito de objetos.

Permite que objetos do mundo real sejam mapeados em Objetos no computador, pressupondo que o mundo é composto por objetos.

Os sistemas são modelados como um conjunto de objetos que interagem entre si.

Sugere a diminuição da distância entre modelagem computacional e o mundo real.

**POO** Consiste em utilizar objetos computacionais para implementar as funcionalidades de um sistema. Já **Análise orientada a objetos** Consiste em definir quais objetos fazem parte de um sistema e a maneira como se comportam.

=== Abstração

- Forma de lidar com a complexidade.

- Construção de um modelo para representação de uma realidade.

- Entender algo no mundo pela construção de modelos mentais.

- Diz repeito às Operações mentais que executamos para observar um domínio e capturar sua estrutura em um modelo conceitual.

A abstração pode ser utilizada em qualquer contexto, objetivando fragmentar e organizar cenários para melhor compreensão do todo.
Representação: convenções de representação que adotamos para um modelo conceitual.

- Ex1: Projeto de construção civil.
- Ex2: Projeto de construção de um sistema.

Com a abstração, podemos observar uma realidade e abstrair uma série de elementos que servirão de base para o desenvolvimento do software.

=== Vantagens da POO

A OO é mais intuitiva e fácil de aprender do que as técnicas tradicionais, pois foca o problema em conceitos do mundo real.
Dentre as vantagens que a OO proporciona, podemos destacar:

- aumento de produtividade;
- reuso de código;
- redução das linhas de código programadas;
- maior flexibilidade do sistema;
- facilidade na manutenção, dentre outras vantagens.

=== A OO introduz e enfatiza os seguintes conceitos

- Objeto
- Classe
- Encapsulamento
- Herança
- Polimorfismo

== Referências

- MELO, Ana Cristina. Desenvolvendo Aplicações com UML 2.0: do conceitual à implementação. 2ª ed. – Rio de Janeiro: Brasport, 2004.

- SBROCCO, José Henrique Teixeira de Carvalho. UML 2.3: teoria e prática. 1ª ed. – São Paulo: Érica, 2011.