:icons: font
:allow-uri-read:
//caminho padrão para imagens
:imagesdir: ../images
:numbered:
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


link:https://fagno.github.io/poo-java/[HOME]

= Programação Orientada a Objetos

Fagno Alves Fonseca <fagno.fonseca@ifto.edu.br>
Mestre em Modelagem Computacional de Sistemas – UFT.

== Interface

Em Java, uma interface é um tipo especial de classe que contém métodos abstratos (sem implementação), métodos padrão (default methods) e constantes. Interfaces, por natureza, são abstratas.

Interfaces definem um padrão e o caminho público para especificação do comportamento de classes. Permitem que classes, independente de sua localização na estrutura hierárquica, implementem comportamentos comuns.

Utilizamos interfaces quando queremos classes não relacionadas que implementem métodos similares. Através de interfaces, podemos obter semelhanças entre classes não relacionadas sem forçar um relacionamento artificial entre elas.

Como em Java não existe herança múltipla, a interface pode ser um mecanismo alternativo para a herança múltipla, pois permite que às classes implementem várias interfaces.

Assim como nas classes abstratas, os métodos abstratos de uma interface é um contrato que quando assumido por uma classe deve ser implementado. Já os métodos default, as classes herdam automaticamente o comportamento e podem ou não sobrescrever.

O recurso de métodos default permitem que interfaces possam evoluir sem risco de comprometer o legado. 

Os métodos padrão nas interfaces fornecem maior flexibilidade ao permitir a adição de novos métodos sem quebrar o código existente. 

As interfaces em Java são definidas usando a palavra-chave `interface` seguida pelo nome da interface. Por exemplo:


[source, java]
----
public interface MinhaInterface {

    //constantes
    public static final int MIN_VALOR = 0;
    public static final int MAX_VALOR = 100;

    //métodos abstratos
    public void metodo1();
    public void metodo2(String parametro);

    //método padrão/default 
    default void metodo3() {
        System.out.println("Método3 na interface");
    }

}

----


NOTE: Os métodos são abstratos por padrão, portanto, não é necessário usar a palavra-chave `abstract` na declaração dos métodos.

NOTE: As palavras-chave `public static final` é implícita em uma constante de interface, então o uso pode ser opcional.

[source, java]
----
public interface MetodoPagamento {
    void efetuarPagamento(double valor);
}

public class CartaoCredito implements MetodoPagamento {
    public void efetuarPagamento(double valor) {
        // Lógica para pagamento com cartão de crédito
        System.out.println("Pagamento de R$" + valor + " efetuado com cartão de crédito.");
    }
}

public class PagamentoPix implements MetodoPagamento {
    public void efetuarPagamento(double valor) {
        // Lógica para pagamento por pix
        System.out.println("Pagamento de R$" + valor + " efetuado com Pix");
    }
}

public class SistemaPagamentos {
    public static void main(String[] args) {
        MetodoPagamento metodo1 = new CartaoCredito();
        metodo1.efetuarPagamento(100.0);
        
        MetodoPagamento metodo2 = new PagamentoPix();
        metodo2.efetuarPagamento(200.0);
    }
}
----

Sobre o exemplo e vantagens do uso de interface:

- Abstração e encapsulamento: A interface MetodoPagamento define um contrato abstrato que encapsula o comportamento comum a todos os métodos de pagamento. Isso permite que o sistema de pagamentos se concentre nos conceitos essenciais, sem se preocupar com as implementações específicas de cada método de pagamento.

- Flexibilidade e extensibilidade: O uso de interfaces permite adicionar facilmente novos métodos de pagamento ao sistema sem alterar o código existente. Basta criar uma nova classe que implemente a interface MetodoPagamento e fornecer sua própria implementação para o método efetuarPagamento. O restante do código do sistema de pagamentos não precisa ser modificado, pois se baseia na interface em vez de depender de implementações específicas.

- Polimorfismo: Ao usar a interface MetodoPagamento como tipo de referência, podemos tratar os diferentes métodos de pagamento de forma polimórfica. Isso significa que podemos usar a mesma interface para referenciar objetos de classes diferentes que implementam a interface. Isso nos permite escrever código mais genérico, facilitando a manutenção e reutilização do código.


== Referências

- BARNES, David J. e  KOLLING, Michael. Programação orientada a objetos com java: Uma introdução pratica usando o BlueJ. 4ª Edição – São Paulo: Pearson Prentice Hall, 2009.

- MELO, Ana Cristina. Desenvolvendo Aplicações com UML 2.0: do conceitual à implementação. 2a ed. – Rio de Janeiro: Brasport, 2004.
