:icons: font
:allow-uri-read:
//caminho padrão para imagens
:imagesdir: ../images
:numbered:
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


link:https://fagno.github.io/poo-java/[HOME]

= Programação Orientada a Objetos

Fagno Alves Fonseca <fagno.fonseca@ifto.edu.br>
Mestre em Modelagem Computacional de Sistemas – UFT.

== Encapsulamento

Tem a idéia de que a utilização de um sistema orientado a objetos não deve depender de sua implementação interna, e sim de sua interface.

Exemplo: você não precisa conhecer os detalhes dos circuitos de um telefone para utilizá-lo. A carcaça do telefone encapsula esses detalhes, provendo a você uma interface mais amigável (os botões, o monofone e os sinais de tom).

Encapsulamento é um princípio que propõe ocultar determinados elementos de uma classe das demais classes.

A principal motivação para o encapsulamento é facilitar a reutilização de objetos, garantindo maior estabilidade para o sistema de software.

Favorece os testes dos sistemas de software, resultando em um aumento da qualidade do sistema.

O encapsulamento protege o acesso direto aos atributos de uma instância fora da classe onde estes foram declarados.

Ao colocar uma proteção ao redor dos atributos e criar métodos para prover o acesso a estes, desta forma estaremos prevenindo contra os efeitos colaterais indesejados.

Desta forma, não podemos ter acesso direto aos dados diretamente, apenas por intermédio dos métodos.

Um exemplo clássico é o saldo de uma conta bancária. Neste exemplo, é correto definir métodos específicos responsáveis pelos lançamentos de créditos e débitos, encapsulados em uma determinada classe, por exemplo, “conta”.

O saldo da conta fica armazenado em um dos atributos dessa classe, protegido da ação de qualquer outra classe que não pertença à classe “conta”.

Quando estamos criando as nossas classes e definindo as suas propriedades e métodos, devemos implementar algum tipo de restrição para se acessar esses Dados.

Para implementar isso, no Java, temos os modificadores de acesso.

=== Modificadores de acesso

NOTE: Existem somente 3 modificadores de acesso (private, protected e public). Porém, existem 4 níveis de visibilidade (default, private, protected e public).

É sempre dito como boa prática que atributos internos devem ser privados, pois classes externas nem devem saber que ele existe. O que a classe expõe são suas funcionalidades.

- **Private**: A única classe que tem acesso ao atributo é a própria classe que o define, ou seja, se uma classe Pessoa declara um atributo privado chamado nome, somente a classe Pessoa terá acesso a ele.

- **Default**: Tem acesso a um atributo default (identificado pela ausência de modificadores) todas as classes que estiverem no mesmo pacote que a classe que possui o atributo.

- **Protected**: é praticamente igual ao default, com a diferença de que se uma classe (mesmo que esteja fora do pacote) estende(herança) da classe com o atributo protected, ela terá acesso a ele. Então o acesso é por pacote e por herança.

- **Public**: todas as classes tem acesso

=== Métodos Assessores

Para implementar o princípio de encapsulamento, ou seja, não permitir que quaisquer objetos acessem os nossos dados de qualquer modo, declaramos os atributos como privados.

Entretanto, há momentos em que queremos que outros objetos acessem estes dados. Para que possamos fazer isso, criamos métodos assessores.

Os métodos assessores são usados para ler valores de atributos de objeto ou de classe. O método assessor recebe o nome de `get<NomeDoAtributo>`. Ele retorna um valor.

Para o nosso exemplo, queremos métodos que possam ler os dados do cliente.

[source, java]
----
public class Cliente {

    private String nome;
    private String cpf;
    private Endereco endereco;

    public String getNome() {
        return nome;
    }

    public String getCpf() {
        return cpf;
    }

    public Endereco getEndereco() {
        return endereco;
    }

}
----

=== Métodos Modificadores

Para que outros objetos possam modificar os nossos dados, disponibilizamos métodos que possam gravar ou modificar os valores dos atributos ou de classe.

Chamamos a estes métodos modificadores. Este método é escrito como `set<NomeDoAtributoDeObjeto>`.

Métodos modificadores não retornam valores. Entretanto, eles devem receber um argumento com o mesmo tipo do atributo no qual estão tratando.

Para o nosso exemplo, queremos métodos que possa modificar os dados do cliente.


[source, java]
----
public class Cliente {

    private String nome;
    private String cpf;
    private Endereco endereco;

    public void setNome(String nome) {
        this.nome = nome;
    }

    public void setCpf() {
        this.cpf = cpf;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

}
----

== Referências

- BARNES, David J. e KOLLING, Michael. Programação orientada a objetos com java: Uma introdução pratica usando o BlueJ. 4a Edição – São Paulo: Pearson Prentice Hall, 2009.

- SBROCCO, José Henrique Teixeira de Carvalho. UML 2.3: teoria e
prática. 1a ed. – São Paulo: Érica, 2011.